@startuml
'https://plantuml.com/class-diagram

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam roundcorner 10
hide enum methods

class Kingdomino {
    + {static}main()
}

package models {

    interface GameObserver {
        + reactGame(game:Game)
    }

    class Game {
        + Game(players:Player[], deck:Domino[], middle:Boolean, harmony:Boolean)

        - round:Integer

        - middle:Boolean
        - harmony:Boolean

        + getCurrentPlayer():Player
        + setCurrentPlayer(player:Player)
        + getAllPlayers():Player[]

        + nextRound()
        + getRound():Integer

        + getDraw(): Domino[]
        + getLastDraw(): Domino[]
        + setDraw(draw:Domino[])

        + getDeck(): Domino[]

        + isMiddle():Boolean
        + isHarmony():Boolean

        + notifyObservers()
        + addObserver(observer:GameObserver)
    }

    class Player {
        + Player(name:String, color:Colors, numberOfKings:Integer)
        - name:String

        + getName():String
        + getColor():Colors
        + getKings():King[]
        + getKingdom():Kingdom
    }

    class King {
        + isPlaced:Boolean
        + King(parent:Player)
        + getParent():Player
    }

    class Kingdom {

        + {static}gridSize:Integer

        + Kingdom(parent:Player)
        + getParent():Player

        + getKingdom():Tile[5][5]
        + hasCastle():Boolean

        + setPreviews(previews:List<Preview>)
        + applyPreviews()

        + isEmpty(x:Integer, y:Integer)

        + addObserver(observer:KingdomObserver)
        + notifyObservers()
    }

    class Domino {
        + Domino(number:Integer,tile1:Tile, tile2:Tile)
        - number:Integer

        + getNumber():Integer
        + getTile1():Tile
        + getTile2():Tile
    }

    class Tile {
        + Tile(land:Lands, crowns:Integer)
        - crowns:Integer

        + getCrowns():Integer
        + getLand():Lands
    }

    enum Lands {
        WATER
        FOREST
        WHEAT
        GRASS
        SWAMP
        MINE
        CASTLE
    }

    enum Colors {
        BLUE
        GREEN
        YELLOW
        PINK
    }

    enum Orientations {
        SOUTH
        WEST
        EAST
        NORTH
    }

    class Preview {
        - x:Integer
        - y:Integer
        + Preview(tile:Tile, x:Integer, y:Integer)
        + getX():Integer
        + getY():Integer
        + getTile():Tile
    }

    interface KingdomObserver {
        + updateKingdom(kingdom:Kingdom)
    }

    interface MovableInterface {
        + moveRight()
        + moveLeft()
        + moveUp()
        + moveDown()
        + canGoRight():Boolean
        + canGoLeft():Boolean
        + canGoDown():Boolean
        + canGoUp():Boolean
    }

}

package views {

    class GameView implements GameObserver {
        + GameView(controller:GameController, game:GameView)
        + setAction(text:String, content)
        + reactGame(game:Game)
    }

    class StartMenu {
        - playerFrame:JPanel
        - removePlayerButton:JButton
        - addPlayerButton:JButton
        + StartMenu(controller:GameCreator)
        + isMiddle():Boolean
        + isHarmony():Boolean
        + refreshPlayers(players:PlayerEditor[])
    }

    class EndMenu {
        + EndMenu(game:Game)
    }

    class PlayerEditor {
        + PlayerEditor()
        + getPlayerName():String
        + getPlayerColor():Colors
        + setPlayerColor(color:Colors)
    }

    class KingdomView {
        + KingdomView(kingdom:Kingdom)
        + updateKingdom(kingdom:Kingdom)
    }

    class DrawView {
        + DrawView(dominos:Domino[], title:String, controller:GameController)
        + showButtons()
    }

    class DominoView {
        + DominoView(domino:Domino)
        + getDomino():Domino
    }

    class TileView {
        + {static}tileSize:Integer
        + TileView(tile:Tile)
        + getTile():Tile
    }

    class KingDominoDesign {
        + {static}BLUE:Color
        + {static}GREEN:Color
        + {static}YELLOW:Color
        + {static}PINK:Color
        + {static}RED:Color
        + {static}PURPLE:Color
        + {static}BLACK:Color

        + {static}textLg:Float
        + {static}textMd:Float
        + {static}textBase:Float
        + {static}textSm:Float

        + titleFont:Font
        + textFont:Font

        - {static}instance:KingDominoDesign

        - KingDominoDesign()

        + {static}getInstance():KingDominoDesign
        + {static}getColor(color:Colors)

    }

    class CastlePlacement {
        - placeButton:Button
        + CastlePlacement(controller:CastleController)
        + getArrows():PositionArrows
        + getPlaceButton():Button
    }

    class DominoPlacement {
        - placeButton:Button
        + DominoPlacement(controller:DominoController)
        + getArrows():PositionArrows
        + getPlaceButton():Button
    }

    class PositionArrows {
        - leftButton:Button
        - rightButton:Button
        - upButton:Button
        - downButton:Button
        + PositionArrows()
        + getLeftButton():Button
        + getRightButton():Button
        + getUpButton():Button
        + getDownButton():Button
        + bindActions(controller:MovableInterface)
    }

    class KingView {
        + KingView(color:Colors)
    }

}

package controllers {

    class GameController {
        - placedCastles:Boolean
        + GameController(game:Game, creator:GameCreator)
        + setView(view:GameView)
        + setDrawView(drawView:DrawView)
        + play()
        + makeDraw()
        + playerPlaceCastle()
        + playerChooseDomino(king:King)
        + dominoChosen(domino:Domino)
        + playerPlaceDomino()
        + exitGame()
    }

    class GameCreator {

        + GameCreator(dominos:Domino[])

        + setView(view:StartMenu)

        + canAddPlayer():boolean
        + canRemovePlayer():boolean

        + addPlayer()
        + removePlayer()
        + getPlayers():Player[]

        + createGame(view:StartMenu)
    }

    class DominoController implements MovableInterface {
        + DominoController(kingdom:Kingdom)
        + moveRight()
        + moveLeft()
        + moveUp()
        + moveDown()
        + canGoRight():Boolean
        + canGoLeft():Boolean
        + canGoDown():Boolean
        + canGoUp():Boolean
        + rotate()
        + invert()
        + place()
        + setView(view:DominoPlacement)
    }

    class CastleController implements MovableInterface {
        - x:Integer
        - y:Integer
        + CastleController(kingdom:Kingdom, parentController:GameController)
        + moveRight()
        + moveLeft()
        + moveUp()
        + moveDown()
        + canGoRight():Boolean
        + canGoLeft():Boolean
        + canGoDown():Boolean
        + canGoUp():Boolean
        - updatePreview()
        + place()
        + setView(view:CastlePlacement)
    }

    abstract class CSVReader {
        - {static} csvToListString():String[]
        - {static} splitString(line:String):String[]
        - {static} setDominos(listStringDomino:String[])
        + {static} getDominos():Domino[]
    }

}

Kingdomino ..> StartMenu : "<<use>>"
Kingdomino ..> GameCreator : "<<use>>"
Kingdomino ..> CSVReader : "<<use>>"

GameCreator " - dominos" o--> "*" Domino : > contains
GameCreator " - players" *--> "2, 3" PlayerEditor : > contains
GameCreator " - view" o--> "1" StartMenu : > contains
GameCreator ..> Game : "<<use>>"
GameCreator ..> GameView : "<<use>>"
GameCreator ..> GameController : "<<use>>"

Game " - players" *--> "2, 4" Player : > contains
Game " - deck" *--> "0, 48" Domino : > contains
Game " - draw" *--> "3, 4" Domino : > contains
Game " - lastDraw" *--> "3, 4" Domino : > contains
Game " - observers" o--> "*" GameObserver : > contains
Game " - currentPlayer" o--> Player : > knows

GameController " - game" o--> Game : > controls
GameController " - view" o--> GameView : > contains
GameController " - drawView" o--> DrawView : > contains
GameController ..> CastlePlacement : <<use>>
GameController ..> DominoPlacement : <<use>>
GameController ..> EndMenu : "<<use>>"

DominoPlacement " - arrows" *--> "1" PositionArrows : > contains
DominoPlacement " - controller" o--> "1" DominoController : > contains

CastlePlacement " - arrows" *--> "1" PositionArrows : > contains
CastlePlacement " - controller" o--> "1" CastleController : > contains

GameView " - controller" o--> GameController : > controlled by
GameView ..> Game : "<<use>>"
GameView ..> KingdomView : "<<use>>"
GameView ..> DrawView : <<use>>

StartMenu " - controller" o--> "1" GameCreator : > controlled by

EndMenu ..> Game : "<<use>>"
EndMenu ..> StartMenu : "<<use>>"

Player " - kingdom"  *--> Kingdom : > owns
Player " - kings" *--> "1,2" King : > contains
Player " + currentKing" *--> "1" King : > contains
Player " - color" *-> Colors : > has

King " - parent" o--> Player : > knows

Kingdom " - parent" o--> Player : > knows
Kingdom " - board" o--> "[5][5]" Tile : > contains
Kingdom " - observers" o--> "*" KingdomObserver : > contains
Kingdom " - previews" *--> "*" Preview : > contains

CastleController " - kingdom" o--> "1" Kingdom : > contains
CastleController " - view" o--> "1" CastlePlacement : > contains
CastleController " - parentController" o--> "1" GameController : > contains

DominoController " - kingdom" o--> "1" Kingdom : > contains
DominoController " - view" o--> "1" DominoPlacement : > contains

KingdomView ..> DominoView : <<use>>

DrawView ..> DominoView : "<<use>>"

DominoView " - domino" o--> "1" Domino : > contains
DominoView ..> TileView : <<use>>

Domino " - tile1" o-> Tile : > contains
Domino " - tile2" o-> Tile : > contains
Domino " + king" o--> King : > contains

Tile *-> Lands : " - type" > is

TileView " -tile" o--> "1" Tile : > contains

Preview " - tile" o--> "1" Tile : > contains


@enduml